### PR TITLE
fix publisher potentially undefined in publicationListElement

### LINKED ISSUE #1810: List View breaks with no publishers in metadata
Thorium v2.1.0 goes blank, if there are no publishers in the `publications[].metadata`:

# Steps to Reproduce
1. Connect to a OPDS feed without publishers in metadata.
2. Switch List View by clicking the icon to the left of the search bar.
3. Thorium goes grey.

It is caused by this:
https://github.com/edrlab/thorium-reader/blob/v2.1.0/src/renderer/library/components/publication/PublicationListElement.tsx#L75-L83

## Example Opds with the problem:
```json
{
  "metadata": {
    "@type": "http://schema.org/DataFeed",
    "title": "OPDS 2.0 Feed",
    "currentPage": 1,
    "itemsPerPage": 50,
    "numberOfItems": 1
  },
  "links": [
    {
      "href": "http://localhost:5000/opds2/search/?query=37027&page=1&size=50",
      "rel": "self",
      "type": "application/opds+json"
    }
  ],
  "publications": [
    {
      "metadata": {
        "@type": "http://schema.org/Book",
        "title": "Bunker 137",
        "author": {
          "name": "Michael Kamp",
          "identifier": "merkur:author:183549",
          "links": [
            {
              "title": "Michael Kamp",
              "href": "/opds2/search/merkur:author:183549/info.json",
              "rel": "search",
              "type": "application/opds+json",
              "properties": {
                "x-identifier": "merkur:author-info:183549"
              }
            }
          ]
        },
        "identifier": "merkur:libraryid:37027",
        "language": "da",
        "modified": "2011-11-15T00:00:00.0000000+00:00",
        "x-download-size-in-bytes": 415232979,
        "x-entity-group-identifier": "794715-30711233--1-da",
        "x-has-text": true,
        "x-is-audio-book": true,
        "x-is-ebook": true,
        "x-library-id": "37027",
        "x-published": "2011-11-15T00:00:00Z",
        "x-target-audience": "Young"
      },
      "links": [
        {
          "href": "/opds2/publication/merkur:libraryid:37027/details.json",
          "rel": "details",
          "type": "application/opds+json",
          "properties": {
            "x-identifier": "merkur:libraryid:37027"
          }
        },
        {
          "href": "/opds2/publication/merkur:libraryid:37027.json",
          "rel": "self",
          "type": "application/opds-publication+json",
          "properties": {
            "x-identifier": "merkur:libraryid:37027"
          }
        },
        {
          "href": "/opds2/publication/merkur:libraryid:37027/download?format=epub",
          "rel": "http://opds-spec.org/acquisition",
          "type": "application/epub+zip"
        },
        {
          "href": "/opds2/publication/merkur:libraryid:37027/manifest.json",
          "rel": "manifest",
          "type": "application/webpub+json"
        }
      ],
      "images": [
        {
          "href": "https://bookcover.nota.dk/37027.jpg",
          "rel": [
            "http://opds-spec.org/image",
            "cover"
          ],
          "type": "image/jpeg"
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by panaC**
fixes #1810

### CODE REVIEW

File: src/renderer/library/components/publication/PublicationListElement.tsx [hunk 1]
```diff
@@ -70,22 +70,38 @@ export class PublicationListElement extends React.Component<IProps, IState> {
...
-                    if ((cv as IOpdsContributorView)?.name) {
-                        return [...pv, `${pv}${(cv as IOpdsContributorView).name}`];
-                    }
-                    return cv && typeof cv === "string" ? [...pv, cv] : pv;
-                }, [])
-            .join(", ");
-        let formatedPublishedYear = "";
+        const publishers = pub.publishers;
+        const publishedAt = pub.publishedAt;
+        const isPublishers = !!publishers || !!publishedAt;
```
Comment (danielweck) [inline src/renderer/library/components/publication/PublicationListElement.tsx:77]: if `pub.publishers` is not an array (e.g. undefined/null), and `pub.publishedAt` is truthy, then the line below crashes: `for (const publisher of publishers)`, right?

Comment (danielweck) [reply src/renderer/library/components/publication/PublicationListElement.tsx:77]: `TypeError: v is not iterable`

**Review by danielweck — CHANGES_REQUESTED** [review]
