### PR TITLE
fixes #2329 fixes #2344

### LINKED ISSUE #2329: delete single bookmark in list (while in edit mode or not) causes crash (works fine with annotations editor)
Screenshot 2024-05-23 at 14 40 59

### LINKED ISSUE #2344: bookmarks and annotations list pagination logic breaks when deleting items
follow-up to https://github.com/edrlab/thorium-reader/pull/2332#issuecomment-2129258465

### PR DESCRIPTION
**Pull request by panaC**

### CODE REVIEW

File: src/renderer/reader/components/ReaderMenu.tsx [hunk 1]
```diff
@@ -613,6 +615,9 @@ const AnnotationList: React.FC<{ r2Publication: R2Publication, dockedMode: boole
         }
     }, [isSearchEnable]);
 
+    if (!r2Publication || !annotationsQueue) {
```
Comment (danielweck) [inline src/renderer/reader/components/ReaderMenu.tsx:618]: `!annotationsQueue?.length`, I think

File: src/renderer/reader/components/ReaderMenu.tsx [hunk 2]
```diff
@@ -581,6 +578,11 @@ const AnnotationList: React.FC<{ r2Publication: R2Publication, dockedMode: boole
     };
 
     const [pageNumber, setPageNumber] = React.useState(getStartPage);
+    React.useEffect(() => {
+        if (pageNumber > pageTotal) {
+            setPageNumber(pageTotal);
+        }
+    }, [pageTotal]);
```
Comment (danielweck) [inline src/renderer/reader/components/ReaderMenu.tsx:585]: dependency array, missing `pageNumber`?

File: src/renderer/reader/components/ReaderMenu.tsx [hunk 3]
```diff
@@ -914,6 +915,12 @@ const BookmarkList: React.FC<{ r2Publication: R2Publication, dockedMode: boolean
     const pageTotal =  Math.floor(sortedBookmarks.length / MAX_MATCHES_PER_PAGE) + ((sortedBookmarks.length % MAX_MATCHES_PER_PAGE === 0) ? 0 : 1);
 
     const [pageNumber, setPageNumber] = React.useState(1);
+    React.useEffect(() => {
+        if (pageNumber > pageTotal) {
+            setPageNumber(pageTotal);
+        }
+    }, [pageTotal]);
```
Comment (danielweck) [inline src/renderer/reader/components/ReaderMenu.tsx:922]: dependency array, missing `pageNumber`?

**Review by danielweck — CHANGES_REQUESTED** [review]

File: src/renderer/reader/components/ReaderMenu.tsx (hunk 2 above)
Comment (panaC) [reply src/renderer/reader/components/ReaderMenu.tsx:585]: I don't think so, I want to trigger the test on pageTotal change

File: src/renderer/reader/components/ReaderMenu.tsx (hunk 1 above)
Comment (panaC) [reply src/renderer/reader/components/ReaderMenu.tsx:618]: I don't think so either

**Comment by panaC** [comment]
I note a new bug about the bookmark docked component on refresh when i delete a bookmark and i make a new, the component is not DOM refreshed but logically refresh in local state, doesn't appear in annotation, just bookmark

File: src/renderer/reader/components/ReaderMenu.tsx (hunk 1 above)
Comment (panaC) [reply src/renderer/reader/components/ReaderMenu.tsx]: removed

Comment (danielweck) [reply src/renderer/reader/components/ReaderMenu.tsx]: falsy `annotationsQueue` from IReaderRootState[reader.annotation] results in empty JSX, but empty array too, no?

File: src/renderer/reader/components/ReaderMenu.tsx (hunk 2 above)
Comment (danielweck) [reply src/renderer/reader/components/ReaderMenu.tsx:585]: doesn't this break rules of hooks?

> The array of dependencies is not passed as arguments to the effect function. Conceptually, though, that’s what they represent: every value referenced inside the effect function should also appear in the dependencies array. In the future, a sufficiently advanced compiler could create this array automatically

https://legacy.reactjs.org/docs/hooks-reference.html

**Review by danielweck — CHANGES_REQUESTED** [review]

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/pull/2345#discussion_r1613388858


no not at all, use here as subscriber, 

if pageNumber is passed as a dependency this allows you to have a "garde fou" on pageNumber

File: src/renderer/reader/components/ReaderMenu.tsx (hunk 2 above)
Comment (danielweck) [reply src/renderer/reader/components/ReaderMenu.tsx:585]: > make sure the array includes all values from the component scope (such as props and state) that change over time and that are used by the effect. Otherwise, your code will reference stale values from previous renders.

https://legacy.reactjs.org/docs/hooks-reference.html

Comment (panaC) [reply src/renderer/reader/components/ReaderMenu.tsx:585]: `pageTotal` n'est ni un état ni un props 🙃

Comment (danielweck) [reply src/renderer/reader/components/ReaderMenu.tsx:585]: any value within the closure scope (i.e. render function, given that hooks are always top-level) that participates to computations inside the hook's closure should be declared explicitly as a dependency (in fact a linter would probably yell at us for not following this rule).
but I don't fully understand what the logic is here so you probably have something in mind that justifies firing the effect for only a subset of conputation dependencies?

Comment (danielweck) [reply src/renderer/reader/components/ReaderMenu.tsx:585]: ok, let's merge this PR, I trust you judgement regarding the runtime logic.
