### PR TITLE
chore(dev): enhance readerState typing between main registry/session and renderer & fix the 'delete' object key in registry push action

### LINKED ISSUE #1444: Redux anti-pattern: state payload modified in action creator, not reducer
https://github.com/edrlab/thorium-reader/blob/58ef86ddb581ce37ba706f117ab986a9bbca2d30/src/main/redux/actions/win/registry/registerReaderPublication.ts#L23-L25

### LINKED ISSUE #2947: Redux anti-pattern: state payload modified in action creator, not reducer
### Discussed in https://github.com/edrlab/thorium-reader/discussions/1762

<div type='discussions-op-text'>

<sup>Originally posted by **danielweck** April 27, 2021</sup>
https://github.com/edrlab/thorium-reader/blob/58ef86ddb581ce37ba706f117ab986a9bbca2d30/src/main/redux/actions/win/registry/registerReaderPublication.ts#L23-L25</div>

### PR DESCRIPTION
**Pull request by panaC**
Fixes #1762
Fixes #1444
Fixes #2947

### CODE REVIEW

File: src/main/redux/actions/win/registry/registerReaderPublication.ts [hunk 1]
```diff
@@ -7,27 +7,19 @@
...
+export function build(publicationIdentifier: string, bound: Rectangle, reduxStateReader: Partial<IReaderStateReaderPersistence>):
     Action<typeof ID, Payload> {
 
-    // https://github.com/edrlab/thorium-reader/issues/1444
-    // TODO:
-    // see initStore() in main/redux/store/memory.ts
-    // !!
-    delete reduxStateReader.highlight;
-    // https://github.com/edrlab/thorium-reader/blob/fd9d82beb95d5d2ee4c927a2eed91ebf3ffa8424/src/main/redux/actions/win/session/registerReader.ts#L57
-    delete reduxStateReader.info;
```
Comment (panaC) [inline src/main/redux/actions/win/registry/registerReaderPublication.ts:29]: `delete reduxStateReader.info;` is not necessary now, thanks to : 
https://github.com/edrlab/thorium-reader/pull/2946/files#diff-7de918470e1f77df422151ca5c658e410828cc273ad1b7abfc91a77d38251c8eR141-R145

do not update readerStatePersistence on reader closing, the state must not be updated from readerStateSession

**Comment by panaC** [comment]
Lots of `Partial` type on both `registry` and `session` means lots of  sanitize work with `[StrictNullChecks](https://www.typescriptlang.org/tsconfig/#strictNullChecks)` :) I hope one day !

I'm merging now @danielweck feel free to double check again Please !

**Comment by danielweck** [comment]
makes sense! thank you
