### PR TITLE
display navigation arrows in reader scroll vies

### LINKED ISSUE #2248: reader scroll view feature regression: left/right pagination arrow buttons are not displayed
without the visual buttons, the only way to scroll HTML documents by a single viewport extent unit is to use the keyboard arrow keys (or press the space bar, assuming keyboard focus inside the scrolling viewport)

Screenshot 2024-05-20 at 09 50 13

Screenshot 2024-05-20 at 09 50 45

### PR DESCRIPTION
**Pull request by arthur-lemeur**
Fixes #2248

### CODE REVIEW

File: src/renderer/reader/components/Reader.tsx [hunk 1]
```diff
@@ -736,8 +736,8 @@ class Reader extends React.Component<IProps, IState> {
         
         const isAudioBook = isAudiobookFn(this.props.r2Publication);
         const arrowDisabledNotEpub = isAudioBook || this.props.isPdf || this.props.isDivina;
-        const isFXL = this.isFixedLayout();
-        const isPaginated = this.props.readerConfig.paged;
+        // const isFXL = this.isFixedLayout();
```
Comment (danielweck) [inline src/renderer/reader/components/Reader.tsx:739]: Oh, I didn't even realise that the previous/next arrows had been disabled for fixed-layout / pre-paginated publications! Good catch thanks
