### PR TITLE
fix: bookmark auto-numbering and initialise/migrate created/modifed/creator bookmark data state 

### LINKED ISSUE #2860: bookmark auto-numbering is very confusing, tied to GUI list item order, not actual data model
For example, when deleting "Bookmark 1", it seems to re-appear because the numbering is dynamic for the displayed GUI list, it is not intrinsic to the bookmark data model itself.

Discussion:
https://github.com/edrlab/thorium-reader/issues/2829#issuecomment-2704696235

### PR DESCRIPTION
**Pull request by panaC**
fixes #2860

### CODE REVIEW

File: src/renderer/reader/index_reader.ts [hunk 1]
```diff
@@ -78,6 +80,31 @@ ipcRenderer.on(readerIpc.CHANNEL,
...
+                for (const [created, bookmark] of bookmarkList) {
+                    bookmarkIndex = bookmarkIndex + 1;
+                    if (!bookmark.created && created > bookmark.modified) {
+                        bookmark.created = bookmark.modified;
+                    }
+                    if (!bookmark.created) {
+                        bookmark.created = created;
+                    }
+                    if (!bookmark.name) {
+                        bookmark.name = `bookmark_${bookmarkIndex}`; // TODO? Probably translation issue !?
```
Comment (panaC) [inline src/renderer/reader/index_reader.ts:104]: @danielweck do you have an idea to deal with bookmark no name migration ? In this PR we force the name of the bookmark to not rely of the bookmark index list position for the naming in UI if no name is available.

**Comment by panaC** [comment]
@danielweck I'm merging this PR, feel free to open any issues that you want :)

**Comment by panaC** [comment]
quick space hit of the bookmark button : 
image

File: src/renderer/reader/index_reader.ts (hunk 1 above)
Comment (danielweck) [reply src/renderer/reader/index_reader.ts:104]: I think the affordance that renders empty bookmark names (like empty annotation descriptions) must make it clear that this is empty. No need for a placeholder, let alone an arbitrary number bound to the list position (which can vary depending on filtering, ordering, etc.)

Comment (panaC) [reply src/renderer/reader/index_reader.ts:104]: seems fine, just this in this case : 
```
bookmark.name = `${bookmarkIndex}`;
```

Comment (panaC) [reply src/renderer/reader/index_reader.ts:104]: https://github.com/edrlab/thorium-reader/commit/6307e4ab4406b2af8ece81a3b19af64f173386ac
