### PR TITLE
fix unmount cycle of toast component

### LINKED ISSUE #3448: [ui] Toast notification wrapper remains non-empty after the toast is removed and blocks clicks on Settings
https://github.com/edrlab/thorium-reader/blob/af6386584fb2d67b24e09b3df67cec59df76210b/src/renderer/common/components/toast/Toast.tsx#L106

componentWillRemove -> componentWillUnmount

https://github.com/edrlab/thorium-reader/blob/af6386584fb2d67b24e09b3df67cec59df76210b/src/renderer/common/components/toast/Toast.tsx#L95

`handleTransitionEnd` can never properly unmount and remove the toast notifcation when the dom event not fired.

### PR DESCRIPTION
**Pull request by arthur-lemeur**
Fixes #3448

### CODE REVIEW

**Review by panaC — CHANGES_REQUESTED** [review]
Good, but doesn't fix the issue

**Comment by danielweck** [comment]
> Good, but doesn't fix the issue

@panaC , @arthur-lemeur pushed another commit, does it work now?

File: src/renderer/common/components/toast/Toast.tsx [hunk 1]
```diff
@@ -132,6 +126,7 @@ export class Toast extends React.Component<IProps, IState> {
 
         return (
             <div
+                onTransitionEnd={this.handleTransitionEnd}
```
Comment (panaC) [inline src/renderer/common/components/toast/Toast.tsx:135]: If the event is not fired, the this.props.close function from the ToastManager component will never be called, meaning the toast will not be unmounted and its reference will not be removed.

**Comment by danielweck** [comment]
@panaC will you have time early this week to confirm that this PR works? It would be great to fix the bug in 3.4.0

**Comment by panaC** [comment]
@danielweck There is still an issue with the `transitionend` [event ](https://developer.mozilla.org/en-US/docs/Web/API/Element/transitionend_event) may not fire in some cases.
It would be more robust to handle all related transition events, including `transitionrun`, `transitionstart`, and `transitioncancel`.
Currently, the toast removal logic relies solely on the `transitionend` event. If this event is not triggered, a div overlay can block interaction with the settings button (except near its border).
To make this more reliable, I think it would be safer to include a fallback mechanism like a timeout, to ensure the toast state stays in sync with the UI.

**Review by panaC — CHANGES_REQUESTED** [review]
See my last message.

**Review by panaC — APPROVED** [review]
