### PR TITLE
fix accessibility

### LINKED ISSUE #2698: Missing Title for Delete annotation button (Trash icon)
Other buttons in this bar have title argument. It is missing for the trash icon.

image

### LINKED ISSUE #2700: Missing titles for reader.annotations.type. in the navigation panel
The icons for annotation type have titles in the Annotation windows but not in the navigation panel filtering options.

image

### LINKED ISSUE #2709: Does screen reader users have use of slider buttons?
Thorium Home library windows displays Recently opened and recently added titles.

The view of shown titles can be moved right or left with sliders but is also automatically moved when tabbing between titles. 

Therefore, the sliders buttons are of no use for keyboard users and introduce an additional complexity for screen reader users who have access to a button that changes nothing to them (next tab will always return to the first title from that pseudo list, notto the first seen one). 

I suggest to `aria-hidden` those buttons.

### LINKED ISSUE #2710: Button for speech speed has no accessible name
The button for adjusting the speech speed has no accessible name. I use a screen reader (JAWS) because I am visually impaired.

### LINKED ISSUE #2711: Unknown checkbox in tools bar, no accessible name
In the tools bar on the right side of the boookmark checkbox there is a checkbox that has no accessible name.
I use a screen reader (JAWS) because I am visually impaired.
My screen reader just says "Checkbox not checked, dialogue".

### LINKED ISSUE #2714: Library grid view uses table for presentation.
We should probably use role=presentation on the table elements to make sure AT users don't get lost looking for unexisting columns.
image

We should test side effects before merging such change

### LINKED ISSUE #2715: Home view Recent lists should be semantic lists instead of divs.
image

### LINKED ISSUE #2718: Blocked aria-hidden on covers from the home page
image

From AXE A11Y checker

> index_library.html#/home:1 Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
> Element with focus: img
> Ancestor with aria-hidden:  ​flex

redundant on each cover image

I guess deleting `aria-hidden=​"true"` should be a sufficient fix because `role=​"presentation"` already does the job

### LINKED ISSUE #2724: Empty navigation means should be unavailable
The Navigation panel starts with a dropdown menu to select a navigation mean (TOC, landmark, gotopage, annotation, bookmark). When one of those means have no entry, it is still reachable and present an empty panel. 

To prevent users from searching to understand where they are, when a navigation mean is empty, it should not be reachable. 

screenshot showing an empty landmark navigation

### LINKED ISSUE #2728: Generic or no aria label "menu" on annotation toolbar icons
The annotation toolbar buttons functions are not rendered to screen reader users because they all have the same generic aria label "menu" (sorting and filtering) or no aria label (import, export, delete, options).

screenshot with code

image

### LINKED ISSUE #2729: Annotations lists are not tagged as semantic list
The annotation panels display annotations as a list, but they are not semantically identified. 

![screenshot with code: <div class="annotations_line" style="border-left: 4px solid rgb(212, 196, 251);"><div class="annnotation_container"><button class="annotation_name R2_CSS_CLASS__FORCE_NO_FOCUS_OUTLINE" aria-label="Go to ... &quot;Solid background&quot;" id="9c7f444f-f52a-4616-aebc-8613c5607a1c"><p>Solid background</p></button><p><span></span><br></p></div><div class="annotation_edit"><div><div><svg aria-hidden="true" viewBox="0 0 14 14"><use xlink:href="#calendar-icon"></use></svg><p>19/12/2024</p></div><div><svg aria-hidden="true" viewBox="0 0 14 13"><use xlink:href="#bookOpen-icon"></use></svg><p>59% </p></div></div><div class="annotation_actions_buttons"><button id="annotation_card-9c7f444f-f52a-4616-aebc-8613c5607a1c_edit_button" title="Edit"><svg aria-hidden="true" viewBox="0 0 11 11"><use xlink:href="#pen-icon"></use></svg></button><button title="Delete" type="button" aria-haspopup="dialog" aria-expanded="false" aria-controls="radix-:r16v:" data-state="closed"><svg aria-hidden="true" viewBox="0 0 16 18"><use xlink:href="#trash-icon"></use></svg></button></div></div><div class="gauge"><div class="fill" style="width: 58.99%;"></div></div></div>](https://github.com/user-attachments/assets/a2339498-fbb9-462d-884b-c04b2500165d)

### LINKED ISSUE #2731: Colour, Creator and modification date are not available in Annotations list
In the annotations panel, each annotation contains the text of the annotation, the creation date, the position in the book expressed in progression percentage and an Edit and a Delete buttons.

Colour, Creator and Modification date are absent but may be used to sort or filter. Sorting or Filtering by undisplayed values can become a burden for users to understand or choose which filter to apply. 

(The colour is visually available on the left border but not rendered to screen reader users).

### LINKED ISSUE #2735: "go fullscreen" button doesn't actually make thorium-reader take up the full screen (Windows 10)
Platform: Windows 10

When pressing the "go fullscreen" button at the top right, only the UI buttons inside the reader are hidden. This is not actually a fullscreen mode - the windows UI elements are still there. This is distracting and unintuitive. See screenshot.

image

### PR DESCRIPTION
**Pull request by arthur-lemeur**
Fixes #2698 
Fixes #2700 
Fixes #2709
Fixes #2710 
Fixes #2711
Fixes #2715
Fixes #2714
Fixes #2718
Fixes #2724
Fixes #2735
Fixes #2728
Fixes #2729 
Fixes #2731

(PS : The "Tag" element from React Aria does not allow for a "title" attribute ([https://react-spectrum.adobe.com/react-aria/TagGroup.html#tag]), I updated the "textValue" attribute (rendered as "aria-label") to be localised instead. According to the documentation, this is the attribute used for accessibility on this element.)

### CODE REVIEW

**Comment by gautierchomel** [comment]
Aria is used by assistive technologies and, therefore, targets a subset of readers with accessibility needs. It is always better to have an accessible name available for all readers (as title) instead of a specific user agent.

**Review by gautierchomel — APPROVED** [review]

**Comment by gautierchomel** [comment]
Any way I can't find the _"textValue" attribute (rendered as "aria-label")_ in that PR.

File: src/renderer/reader/components/ReaderMenu.tsx [hunk 1]
```diff
@@ -1043,7 +1043,7 @@ const AnnotationList: React.FC<{ annotationUUIDFocused: string, resetAnnotationU
                                                 </div>
                                             </summary>
                                             <TagList items={selectDrawtypesOptions} className={stylesAnnotations.annotations_filter_taglist}>
-                                                {(item) => <Tag id={item.name} className={stylesAnnotations.annotations_filter_drawtype} textValue={item.name}><SVG svg={item.svg} /></Tag>}
+                                                {(item) => <Tag id={item.name} className={stylesAnnotations.annotations_filter_drawtype} textValue={item.title}><SVG svg={item.svg} /></Tag>}
```
[the remark this answers is not in the document]
Comment (arthur-lemeur) [reply src/renderer/reader/components/ReaderMenu.tsx]: Changed to "textValue"

File: src/resources/locales/en.json
Comment (gautierchomel) [inline src/resources/locales/en.json:1]: added those keys to the localisation table in the support pages https://github.com/edrlab/thorium-reader-doc/pull/159/commits/c7453f8c25009fc626f91652f95d5f40d39a6d06

Comment (gautierchomel) [reply src/resources/locales/en.json:1]: Not sure if _Zen mode_ replace _Full screen_. In this case, the old key should be deleted.

**Review by gautierchomel — COMMENTED** [review]
Not sure if Zen mode replace Full screen. In this case, the old key should be deleted.

**Comment by danielweck** [comment]
Hello @arthur-lemeur there are now JSON conflicts since the merge of older PR https://github.com/edrlab/thorium-reader/pull/2694
