### PR TITLE
fix disable go to page tab

### LINKED ISSUE #3325: "Enter page number" input field not accessible by keyboard
Hi!

I cannot move keyboard focus to the input field "Enter page number" using keyboard only.
This field probably needs a tab index.

Using Thorium version 3.3.0 on MacOS. 

screen dump

### PR DESCRIPTION
**Pull request by arthur-lemeur**
Fixes #3325

### CODE REVIEW

**Comment by gautierchomel** [comment]
would close #3284 and #3325

File: src/renderer/reader/components/ReaderMenu.tsx [hunk 1]
```diff
@@ -2973,12 +2973,12 @@ export const ReaderMenu: React.FC<IBaseProps> = (props) => {
...
 
     const GoToPageTrigger =
-        <Tabs.Trigger id="reader-menu-tab-gotopage-trigger" value="tab-gotopage" key={"tab-gotopage"} title={__("reader.marks.goTo")} data-value={"tab-gotopage"}>
+        <Tabs.Trigger id="reader-menu-tab-gotopage-trigger" value="tab-gotopage" key={"tab-gotopage"} title={__("reader.marks.goTo")} data-value={"tab-gotopage"} disabled={!r2Publication.Metadata.NumberOfPages}>
             <SVG ariaHidden svg={TargetIcon} />
             <h3>{__("reader.marks.goTo")}</h3>
         </Tabs.Trigger>;
     const optionGoToPageItem = {
-        id: 4, value: "tab-gotopage", name: __("reader.marks.goTo"), disabled: false,
+        id: 4, value: "tab-gotopage", name: __("reader.marks.goTo"), disabled: !r2Publication.Metadata.NumberOfPages,
```
Comment (danielweck) [inline src/renderer/reader/components/ReaderMenu.tsx]: `isDisabled={!(isFixedLayoutNoPageList || r2Publication.PageList || isDivina || isPdf)}`
